#!/bin/bash
set -e

# grub-mkconfig helper script.
# Copyright (C) 2006,2007,2008,2009  Free Software Foundation, Inc.
#
# GRUB is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# GRUB is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with GRUB.  If not, see <http://www.gnu.org/licenses/>.

. "$pkgdatadir/grub-mkconfig_lib"
. /etc/default/grub

export TEXTDOMAIN=grub
export TEXTDOMAINDIR="${datarootdir}/locale"

CLASS="--class android --class os"
OS="Android"

sub_indent() { echo -e "$submenu_indentation$*"; }

android_entry() {
	local \
		title=$1 \
		menuentry_id=$2 \
		kernel=$3 \
		initrd=$4 \
		disk=$5 \
		cmdline=$6

	sub_indent "menuentry '$(echo "$title" | grub_quote)' ${CLASS} \$menuentry_id_option '$menuentry_id' {"

	save_default_entry | grub_add_tab

	# Use ELILO's generic "efifb" when it's known to be available.
	# FIXME: We need an interface to select vesafb in case efifb can't be used.
	if [ ! "$GRUB_GFXPAYLOAD_LINUX" ]; then
		sub_indent "	load_video"
		grep -qx "CONFIG_FB_EFI=y" "${config}" 2>/dev/null &&
			grep -qx "CONFIG_VT_HW_CONSOLE_BINDING=y" "${config}" 2>/dev/null &&
			sub_indent "	set gfxpayload=keep"

	else
		[ "$GRUB_GFXPAYLOAD_LINUX" = text ] ||
			sub_indent "	load_video"
		sub_indent "	set gfxpayload=$GRUB_GFXPAYLOAD_LINUX"
	fi

	sub_indent "	insmod gzio"
	echo "$disk" | sed "s/^/$submenu_indentation	/gm"
	sub_indent "	linux $kernel $cmdline root=/dev/ram0"
	sub_indent "	initrd $initrd"

	sub_indent "}\n"
}

gen_entry() {
	local entry_string=$1 \
		device \
		src \
		os \
		detected_type \
		initrds \
		ucodes \
		system \
		data \
		cmdline

	shift

	i=1
	while read -rd $'\0' arg; do
		case $i in
		1) device=$arg ;;
		2) src=$arg ;;
		3) os=$arg ;;
		4) detected_type=$arg ;;
		5) initrds=$arg ;;
		6) ucodes=$arg ;;
		7) system=$arg ;;
		8) data=$arg ;;
		9) cmdline=${arg:-$GRUB_CMDLINE_ANDROID} ;;
		*) break ;;
		esac
		i=$((i + 1))
	done < <(sed 's/\xFF0/\xFF\x00/g; s/\xFF\(.\)/\1/g' <<<"$entry_string")

	ucode_list=""
	ucode=""
	disk="$(prepare_grub_to_access_device "$device")"
	boot_device_id="$(grub_get_device_id "$device")"

	unset IFS

	echo "Found $os on $device" >&2

	local type=default \
		MAIN_ENTRY \
		EXTENDED_ENTRIES

	# Extra indentation to add to menu entries in a submenu. We're not in a submenu
	# yet, so it's empty. In a submenu it will be equal to '\t' (one tab).
	submenu_indentation=""

	local title

	entry() {
		android_entry \
			"$title" \
			"${OS}-${src##*/}-${1##*/}-${2##*/}-${type}-${boot_device_id}" \
			"${src}/${1}" \
			"${ucode_list# } ${src}/${2}" \
			"$disk" \
			"$cmdline"
	}

	parse_to_entry() {
		if [ "$type" = "default" ]; then
			MAIN_ENTRY=$(entry "$@")
			type=extended
			submenu_indentation=$grub_tab
		fi

		EXTENDED_ENTRIES="$EXTENDED_ENTRIES\n$(entry "$@")"
	}

	local ucode

	if [ "$src" ]; then
		cmdline="$cmdline SRC=$src"
	fi

	IFS=","
	case "$detected_type" in
	gearlock*)
		for ucode in $ucodes; do
			ucode_list="$ucode_list $src/boot/$ucode"
		done

		ROOT_DEVICE=$device
		if [ "$GRUB_DISABLE_LINUX_UUID" != "true" ]; then
			ROOT_UUID=$(${grub_probe} --device "$device" --target=fs_uuid 2>/dev/null)

			[ "$ROOT_UUID" ] &&
				ROOT_DEVICE="UUID=$ROOT_UUID"
		fi

		cmdline="$cmdline ROOT=$ROOT_DEVICE SYSTEM=$system DATA=$data GEARLOCK=$detected_type"

		local kver
		for kver in $initrds; do
			[ "$type" = "default" ] || title="$os, with kernel-$kver - $system"
			parse_to_entry "boot/kernel-$kver" "boot/initrd-$kver.img"
		done
		;;
	*)
		for ucode in $ucodes; do
			ucode_list="$ucode_list $src/$ucode"
		done

		if [ "$data" ]; then
			cmdline="$cmdline DATA=$data"
		fi

		case "$detected_type" in
		ab | fstab)
			ROOT_DEVICE=$device

			case "$detected_type" in
			fstab) if [ "$GRUB_DISABLE_LINUX_UUID" != "true" ]; then
				ROOT_UUID=$(${grub_probe} --device "$device" --target=fs_uuid 2>/dev/null)
				[ "$ROOT_UUID" ] && ROOT_DEVICE="UUID=$ROOT_UUID"
			fi ;;
			*) ;;
			esac

			cmdline="$cmdline ROOT=$ROOT_DEVICE"

			local slot
			for slot in a b; do
				[ "$type" = "default" ] || title="$os - Slot ${slot^}"
				cmdline="$cmdline androidboot.slot_suffix=_$slot"
				parse_to_entry "kernel_$slot" "initrd_$slot.img"
			done
			;;
		*)

			if [ "$system" ]; then
				cmdline="$cmdline SYSTEM=$system"
			fi

			cmdline="$cmdline ROOT=$device"

			local kernels=$detected_type kernel initrd
			for kernel in $kernels; do
				for initrd in $initrds; do
					[ "$type" = "default" ] || title="$title, with ${kernel##*/}, and ${initrd##*/}"
					parse_to_entry "$kernel" "$initrd"
				done
			done
			;;
		esac
		;;
	esac

	unset IFS

	cat <<EOF

$(echo -e "$MAIN_ENTRY")

submenu '$(echo "Advanced options for $os" | grub_quote)' --class submenu ${CLASS} \$menuentry_id_option '${OS}-${src##*/}-${type}-${boot_device_id}' { 
$(echo -e "$EXTENDED_ENTRIES")
}

EOF
}

while read -r detect_entry; do
	gen_entry "$detect_entry"
done < <(grub-android-prober)
